// Балансовые таблицы. Меняешь — правь spec в docs/superpowers/specs.

export const WORLD = { w: 960, h: 540 };

// Ключевые точки спальни (логические координаты)
export const POINTS = {
  ear: { x: 300, y: 306 }, // ухо Ирины на подушке
  lamp: { x: 470, y: 268 }, // абажур настольной лампы
  outlet: { x: 590, y: 402 }, // розетка для фумигатора
  window: { x: 760, y: 190 }, // центр окна
  curtain: { x: 860, y: 200 }, // штора, за которой прячется Матка
  door: { x: 60, y: 200 }, // щель над дверью слева
  ceiling: 70,
  floor: 450,
};

export const NIGHT = {
  hours: 7, // 23:00 .. 06:00
  hourSeconds: 45,
  startHour: 23,
  sleepPerSecond: 100 / 30,
  sleepLossOnBite: 25,
  wakeSeconds: 5,
  buzzToBiteSeconds: 1.5,
  baseHearts: 3,
  maxHearts: 6,
  lampSleepFactor: 0.5,
  bossHours: [2, 5],
};

export const MOSQUITO_TYPES = {
  squeaker: {
    id: 'squeaker',
    name: 'Пискун',
    minHour: 0,
    weight: 10,
    hp: 1,
    speed: 70,
    radius: 9,
    score: 10,
    biteDamage: 1,
    alpha: 1,
    color: '#8c8c9c',
    wobble: 1,
  },
  darter: {
    id: 'darter',
    name: 'Стрелок',
    minHour: 1,
    weight: 6,
    hp: 1,
    speed: 130,
    radius: 8,
    score: 25,
    biteDamage: 1,
    alpha: 1,
    color: '#b0a060',
    wobble: 0.3,
    dodgeRadius: 70,
  },
  ghost: {
    id: 'ghost',
    name: 'Тихоня',
    minHour: 2,
    weight: 4,
    hp: 1,
    speed: 80,
    radius: 9,
    score: 40,
    biteDamage: 1,
    alpha: 0.15,
    color: '#c8d8ff',
    wobble: 0.8,
  },
  bomber: {
    id: 'bomber',
    name: 'Бомбардир',
    minHour: 3,
    weight: 3,
    hp: 3,
    speed: 45,
    radius: 14,
    score: 50,
    biteDamage: 2,
    alpha: 1,
    color: '#6a4a3a',
    wobble: 0.5,
  },
  gnat: {
    id: 'gnat',
    name: 'Мелочь',
    minHour: 1,
    weight: 5,
    hp: 1,
    speed: 95,
    radius: 5,
    score: 5,
    biteDamage: 1,
    alpha: 1,
    color: '#a0a0a0',
    wobble: 1.5,
    swarm: 5,
  },
  chameleon: {
    id: 'chameleon',
    name: 'Хамелеон',
    minHour: 4,
    weight: 4,
    hp: 1,
    speed: 90,
    radius: 9,
    score: 35,
    biteDamage: 1,
    alpha: 1,
    color: '#5a6a5a',
    wobble: 0.6,
    perchAlpha: 0.25,
    scareRadius: 110,
  },
  queen: {
    id: 'queen',
    name: 'Матка',
    minHour: 99, // только по расписанию боссов
    weight: 0,
    hp: 12,
    speed: 60,
    radius: 20,
    score: 500,
    biteDamage: 2,
    alpha: 1,
    color: '#4a2a4a',
    wobble: 0.4,
    boss: true,
    spawnEvery: 6,
    hideSeconds: 3,
  },
};

export const TOOLS = {
  palm: {
    id: 'palm',
    name: 'Ладонь',
    key: '1',
    kind: 'tap',
    radius: 28,
    cooldown: 0,
    price: 0,
    desc: 'Клик — хлопок. Быстро, но узко.',
  },
  clap: {
    id: 'clap',
    name: 'Хлопок',
    key: '2',
    kind: 'charge',
    radiusMin: 30,
    radiusMax: 90,
    chargeSeconds: 0.8,
    cooldown: 1.2,
    price: 0,
    desc: 'Зажми и отпусти: чем дольше, тем шире.',
  },
  swatter: {
    id: 'swatter',
    name: 'Мухобойка',
    key: '3',
    kind: 'swipe',
    width: 22,
    maxLength: 260,
    cooldown: 1.5,
    price: 150,
    desc: 'Проведи линию — сбивает всех на пути.',
  },
  racket: {
    id: 'racket',
    name: 'Электроракетка',
    key: '4',
    kind: 'hold',
    radius: 60,
    battery: 3,
    recharge: 6,
    cooldown: 0,
    price: 300,
    desc: 'Держи кнопку — бьёт током всё, что коснётся.',
  },
  vacuum: {
    id: 'vacuum',
    name: 'Пылесос',
    key: '5',
    kind: 'hold',
    pullRadius: 180,
    pullForce: 260,
    killRadius: 22,
    cooldown: 0,
    price: 450,
    desc: 'Затягивает комаров к соплу. Шумит: сон не растёт.',
  },
  spray: {
    id: 'spray',
    name: 'Спрей',
    key: '6',
    kind: 'tap',
    radius: 70,
    duration: 4,
    dps: 0.5,
    charges: 3,
    cooldown: 0.5,
    price: 350,
    desc: 'Облако на 4 секунды, 3 заряда в час.',
  },
};

export const DIFFICULTY = {
  budgetBase: 8,
  budgetPerHour: 4,
  budgetPerNight: 0.15,
  gapMax: 3.2,
  gapPerHour: 0.35,
  gapMin: 0.6,
  speedPerHour: 0.05,
  speedPerNight: 0.08,
  queenHpPerNight: 4,
};

export const SCORE = {
  hourSleepBonus: 5, // за каждый % сна
  heartBonus: 200,
  comboStep: 3,
  comboMax: 10,
  coinsPerScore: 100,
};

export const META_SHOP = [
  { id: 'tool_swatter', name: 'Мухобойка', price: 150, kind: 'tool', tool: 'swatter', desc: TOOLS.swatter.desc },
  { id: 'tool_racket', name: 'Электроракетка', price: 300, kind: 'tool', tool: 'racket', desc: TOOLS.racket.desc },
  { id: 'tool_spray', name: 'Спрей', price: 350, kind: 'tool', tool: 'spray', desc: TOOLS.spray.desc },
  { id: 'tool_vacuum', name: 'Пылесос', price: 450, kind: 'tool', tool: 'vacuum', desc: TOOLS.vacuum.desc },
  { id: 'slot3', name: 'Третий слот', price: 200, kind: 'slot', desc: 'Бери в ночь три инструмента.' },
  { id: 'slot4', name: 'Четвёртый слот', price: 400, kind: 'slot', requires: 'slot3', desc: 'Бери в ночь четыре инструмента.' },
  { id: 'heart1', name: 'Терпение +1', price: 200, kind: 'heart', desc: 'Четыре сердца вместо трёх.' },
  { id: 'heart2', name: 'Терпение +1', price: 400, kind: 'heart', requires: 'heart1', desc: 'Пять сердец.' },
  { id: 'heart3', name: 'Терпение +1', price: 600, kind: 'heart', requires: 'heart2', desc: 'Шесть сердец.' },
  { id: 'startsleep', name: 'Тёплое молоко', price: 250, kind: 'startSleep', desc: 'Каждый час начинается с 20 % сна.' },
  { id: 'rarepool', name: 'Опыт', price: 300, kind: 'rarePool', desc: 'Редкие перки доступны с первого часа.' },
];
